<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/WebSocketNotifications/WebSocketNotifications.csproj" />
    <PackageReference Include="KafkaHighThroughput" Version="1.0.0-preview.1" />
  </ItemGroup>
</Project>
